<?xml version="1.0" encoding="utf-8"?>

<xs:schema
        xmlns:xs="http://www.w3.org/2001/XMLSchema"
        xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"
        targetNamespace="http://schemas.xmlsoap.org/soap/envelope/"
        elementFormDefault="qualified">

    <xs:element name="Envelope">

        <xs:complexType>
            <xs:sequence>

                <xs:element name="Body">

                    <xs:complexType>
                        <xs:sequence>

                            <xs:element name="AddResponse">

                                <xs:complexType>
                                    <xs:sequence>

                                        <xs:element name="AddResult"
                                                    type="xs:int"/>

                                    </xs:sequence>
                                </xs:complexType>

                            </xs:element>

                        </xs:sequence>
                    </xs:complexType>

                </xs:element>

            </xs:sequence>
        </xs:complexType>

    </xs:element>

</xs:schema>